name: Retrier Code Quality Assurance
run-name: ${{ github.actor }} is running code quality assurance
on:
  pull_request:
  push:
    branches: master

jobs:
  cs:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install PHP 8.1
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
    - name: Install packages
      run: composer install --no-progress
    - name: Run CS
      run: composer cs

  phpmd:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install PHP 8.1
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
    - name: Install packages
      run: composer install --no-progress
    - name: Run MD
      run: composer md

  util-checks:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install PHP 8.1
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
    - name: Verify namespaces
      run: bash util/verify-namespacing.sh
    - name: Ensure no missing scrict types
      run: bash util/missing-strict-types.sh
