name: Retrier Unit Tests
run-name: ${{ github.actor }} is running tests
on:
  pull_request:
  push:
    branches: main

jobs:
  test-8_0:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install PHP 8.0
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
    - name: Install packages
      run: composer install --no-progress
    - name: Run tests
      run: composer test

  test-8_1:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install PHP 8.1
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
    - name: Install packages
      run: composer install --no-progress
    - name: Run tests
      run: composer test

  test-8_2:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
    - name: Install packages
      run: composer install --no-progress
    - name: Run tests
      run: composer test

  test-8_3:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
    - name: Install packages
      run: composer install --no-progress
    - name: Run tests
      run: composer test
